/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */
#pragma once

#include <jni.h>
#include <assert.h>
#include <atomic>
#include <mutex>

#include "jnigen/jni_helper.h"

// external logger function
void jennySampleErrorLog(JNIEnv* env, const char* error);


namespace java {
namespace lang {
class RuntimeExceptionProxy {

public:
    static constexpr auto FULL_CLASS_NAME = u8"java/lang/RuntimeException";


public:
    static bool initClazz(JNIEnv* env);

    static void releaseClazz(JNIEnv* env);

    static void assertInited(JNIEnv* env) {
        auto initClazzSuccess = initClazz(env);
        assert(initClazzSuccess);
    }

    // construct: public RuntimeException()
    static jobject newInstance(JNIEnv* env) {
        assertInited(env);
        return env->NewObject(getClassInitState().sClazz, getClassInitState().sConstruct_0);
    }
    // construct: public RuntimeException(java.lang.String message)
    static jobject newInstance(JNIEnv* env, jstring message) {
        assertInited(env);
        return env->NewObject(getClassInitState().sClazz, getClassInitState().sConstruct_1, message);
    }
    // construct: public RuntimeException(java.lang.String message, java.lang.Throwable cause)
    static jobject newInstance(JNIEnv* env, jstring message, jthrowable cause) {
        assertInited(env);
        return env->NewObject(getClassInitState().sClazz, getClassInitState().sConstruct_2, message, cause);
    }
    // construct: public RuntimeException(java.lang.Throwable cause)
    static jobject newInstance(JNIEnv* env, jthrowable cause) {
        assertInited(env);
        return env->NewObject(getClassInitState().sClazz, getClassInitState().sConstruct_3, cause);
    }



private:
    ::jenny::LocalRef<jobject> _local;
    ::jenny::GlobalRef<jobject> _global;

public:
    ::jenny::LocalRef<jobject> getThis(bool owned = true) const {
        if (_local) {
            if (owned) {
                return _local;
            } else {
                return ::jenny::LocalRef<jobject>(_local.get(), false);
            }
        } else {
            return _global.toLocal();
        }
    }

    // jni helper constructors
    RuntimeExceptionProxy(jobject ref, bool owned = false): _local(ref, owned) {
       assertInited(::jenny::Env().get());
    }

    RuntimeExceptionProxy(::jenny::LocalRef<jobject> ref): _local(std::move(ref)) {
       assertInited(::jenny::Env().get());
    }

    RuntimeExceptionProxy(::jenny::GlobalRef<jobject> ref): _global(std::move(ref)) {
       assertInited(::jenny::Env().get());
    }

    // construct: public RuntimeException()
    static RuntimeExceptionProxy newInstance() {
        ::jenny::Env env;
        assertInited(env.get());
        return env->NewObject(getClassInitState().sClazz, getClassInitState().sConstruct_0);
    }
    // construct: public RuntimeException(java.lang.String message)
    static RuntimeExceptionProxy newInstance(const ::jenny::LocalRef<jstring>& message) {
        ::jenny::Env env;
        assertInited(env.get());
        return env->NewObject(getClassInitState().sClazz, getClassInitState().sConstruct_1, message.get());
    }
    // construct: public RuntimeException(java.lang.String message, java.lang.Throwable cause)
    static RuntimeExceptionProxy newInstance(const ::jenny::LocalRef<jstring>& message, const ::jenny::LocalRef<jthrowable>& cause) {
        ::jenny::Env env;
        assertInited(env.get());
        return env->NewObject(getClassInitState().sClazz, getClassInitState().sConstruct_2, message.get(), cause.get());
    }
    // construct: public RuntimeException(java.lang.Throwable cause)
    static RuntimeExceptionProxy newInstance(const ::jenny::LocalRef<jthrowable>& cause) {
        ::jenny::Env env;
        assertInited(env.get());
        return env->NewObject(getClassInitState().sClazz, getClassInitState().sConstruct_3, cause.get());
    }



private:
    struct ClassInitState {
        // thread safe init
        std::atomic_bool sInited {};
        std::mutex sInitLock {};
        jclass sClazz = nullptr;

        jmethodID sConstruct_0 = nullptr;
        jmethodID sConstruct_1 = nullptr;
        jmethodID sConstruct_2 = nullptr;
        jmethodID sConstruct_3 = nullptr;


    }; // endof struct ClassInitState

    static inline ClassInitState& getClassInitState() {
        static ClassInitState classInitState;
        return classInitState;
    }

};


/*static*/ inline bool RuntimeExceptionProxy::initClazz(JNIEnv* env) {
#define JENNY_CHECK_NULL(val)                      \
       do {                                        \
           if ((val) == nullptr) {                 \
               jennySampleErrorLog(env, "can't init RuntimeExceptionProxy::" #val); \
               return false;                       \
           }                                       \
       } while(false)

    auto& state = getClassInitState();
    if (!state.sInited) {
        std::lock_guard<std::mutex> lg(state.sInitLock);
        if (!state.sInited) {
            auto clazz = env->FindClass(FULL_CLASS_NAME);
            JENNY_CHECK_NULL(clazz);
            state.sClazz = reinterpret_cast<jclass>(env->NewGlobalRef(clazz));
            env->DeleteLocalRef(clazz);
            JENNY_CHECK_NULL(state.sClazz);

            state.sConstruct_0 = env->GetMethodID(state.sClazz, "<init>", "()V");
            JENNY_CHECK_NULL(state.sConstruct_0);
            state.sConstruct_1 = env->GetMethodID(state.sClazz, "<init>", "(Ljava/lang/String;)V");
            JENNY_CHECK_NULL(state.sConstruct_1);
            state.sConstruct_2 = env->GetMethodID(state.sClazz, "<init>", "(Ljava/lang/String;Ljava/lang/Throwable;)V");
            JENNY_CHECK_NULL(state.sConstruct_2);
            state.sConstruct_3 = env->GetMethodID(state.sClazz, "<init>", "(Ljava/lang/Throwable;)V");
            JENNY_CHECK_NULL(state.sConstruct_3);



            state.sInited = true;
        }
    }
#undef JENNY_CHECK_NULL
   return true;
}

/*static*/ inline void RuntimeExceptionProxy::releaseClazz(JNIEnv* env) {
    auto& state = getClassInitState();
    if (state.sInited) {
        std::lock_guard<std::mutex> lg(state.sInitLock);
        if (state.sInited) {
            env->DeleteGlobalRef(state.sClazz);
            state.sClazz = nullptr;
            state.sInited = false;
        }
    }
}


} // end of namespace java
} // end of namespace lang
