/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */
#include "jnigen/jni/NestedNativeClass.h"


/*
 * Class:     io.github.landerlyoung.jennysampleapp.ComputeIntensiveClass$NestedNativeClass
 * Method:    public java.util.HashMap<java.lang.String,java.lang.String> one(java.lang.String param)
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
jobject NestedNativeClass::one(JNIEnv* env, jobject thiz, jstring param) {
    // TODO: generated method stub.
    return nullptr;
}

/*
 * Class:     io.github.landerlyoung.jennysampleapp.ComputeIntensiveClass$NestedNativeClass
 * Method:    public long nativeInit()
 * Signature: ()J
 */
jlong NestedNativeClass::nativeInit(JNIEnv* env, jobject thiz) {
    // TODO: generated method stub.
    return 0;
}

/*
 * Class:     io.github.landerlyoung.jennysampleapp.ComputeIntensiveClass$NestedNativeClass
 * Method:    public void testOverload()
 * Signature: ()V
 */
void NestedNativeClass::testOverload__(JNIEnv* env, jobject thiz) {
    // TODO: generated method stub.
    
}

/*
 * Class:     io.github.landerlyoung.jennysampleapp.ComputeIntensiveClass$NestedNativeClass
 * Method:    public void testOverload(java.lang.Object o)
 * Signature: (Ljava/lang/Object;)V
 */
void NestedNativeClass::testOverload__Ljava_lang_Object_2(JNIEnv* env, jobject thiz, jobject o) {
    // TODO: generated method stub.
    
}

/*
 * Class:     io.github.landerlyoung.jennysampleapp.ComputeIntensiveClass$NestedNativeClass
 * Method:    public void nativeRelease(long handle)
 * Signature: (J)V
 */
void NestedNativeClass::nativeRelease(JNIEnv* env, jobject thiz, jlong handle) {
    // TODO: generated method stub.
    
}


